name: Publish Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Build, Release and Publish to OSSRH
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: |
        mvn \
        --no-transfer-progress \
        --batch-mode \
        -DreleaseVersion=${{ inputs.releaseVersion }} \
        -DdevelopmentVersion=${{ inputs.developmentVersion }} \
        release:prepare \
        release:perform \
        -P publish
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
    - name: Push tags
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.PAT }}
        tags: true
